# See full list of defaults here: https://github.com/bbatsov/rubocop/blob/master/config/default.yml
# To see all cops used see here: https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true


LineLength:
  Max: 120

Layout/CaseIndentation:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/ModuleLength:
  Max: 150

Metrics/BlockLength:
  Enabled: false

Style/SymbolProc:
  Exclude:
    - 'features/step_definitions/**/*.rb'
