# See full list of defaults here: https://github.com/bbatsov/rubocop/blob/master/config/default.yml
# To see all cops used see here: https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml

AllCops:
  DisplayCopNames: true
  NewCops: enable
  TargetRubyVersion: 3

Layout/CaseIndentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Max: 150

Style/CaseEquality:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolProc:
  Exclude:
    - 'features/step_definitions/**/*.rb'
  