language: ruby
dist: bionic
sudo: required

# Bundler and ruby caching
cache:
 - bundler
 - directories:
   - "/home/travis/.rvm/"

rvm:
  - 3.0.2
apt:
  sources:
    - ubuntu-sdk-team
  packages:
    - gstreamer1.0-plugins-base
    - gstreamer1.0-tools
    - gstreamer1.0-x

before_install:
  - sudo apt-get install jq
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq postfix
  - sudo apt-get install -y dpkg
  - sudo apt-get --only-upgrade install google-chrome-stable
  - google-chrome --version

install: bundle install --jobs=3 --retry=3

env:
  global:
    - ARTIFACTS_DEBUG=0
    - ARTIFACTS_REGION="eu-west-1"
    - CI_ARTIFACTS_PATH="https://s3-eu-west-1.amazonaws.com/howitzer-example-travis/$TRAVIS_REPO_SLUG/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER/"
    - MAILGUN_DOMAIN="mg.strongqa.com"
    - BASIC_SEXY_SETTINGS="mailgun_key=$MAILGUN_PRIVATE_API_KEY,mailgun_domain=$MAILGUN_DOMAIN"

  matrix:
    - DRIVER=headless_chrome SEXY_SETTINGS="$BASIC_SEXY_SETTINGS,driver=$DRIVER"
    - DRIVER=headless_firefox SEXY_SETTINGS="$BASIC_SEXY_SETTINGS,driver=$DRIVER"
    # - secure: "A6lewLaPmy6dqaSB30AfTxOdVXO4pjmerkiKCORLYT+CXa9QRbTvlABdGzkKLCbVNO5GrWI3cqg25n7CisSbKgZGthA6LnneyRK4my8IvMsMDK6zqWyxv3Z0mKFR89ClD0SAzO+qeh/aiKuPuUVPTz7HFR2GwvQlMGYSZhc2p/McWUJvcQOI56QakNdIyVoi1ZQkVeeh8+vQm593wAjs9qzmARvNWRfDay40xN4WOj9DSnylrbFWo7gGIcMihkC076fhY8g3TYNZrC35op3R/+nxZGzlo8RR1Gz5xrROaPLdSx5uZgWI/tfskL3976GXBFPSa+Ih3LBCVL2a82gXre4EcW8m5HgErqeBLQd5wypAw3PeRabYG0P1eUWmDpfYAENLpTzQnblri4d2yETwVH5EyQDBolc5ybDLb4A/khF9etlw+ea5g+udD0h6mLfrNQj43ApyoLsTOl6itwHoebQG9qkpnkbRiQX1ucXu4DAPo3E7gA8WrTjIpKPBTcl46NhtTrfEWptqRJoXpir33PDHKlPy/DlrY/KnzhSiFuDrVWz994cCQTL8BV7BU1ADLQZyp+YEwp9T15A1xdJGJBGO17cgmFF6Jv7BtV0rOMr5NDv5U2qtCLMVvvcCcsboqBBbbhLtDUf34SWFcRnSBPDffTqoZQE9B4LYz/SbD3s="
    # #SEXY_SETTINGS=driver=headless_chrome,mailgun_api_key=secret,mailgun_key=secret
    # - secure: "dRL0Y4dwe46GsRc7YU6LTleQ994dvPBPk7eklGqsuP8+deimcO1779gV2TtN+dbjTg9hIIjzRp5f/I+KrL8m9iJFy4XjBtFtBnv4VmAyR0aHWxco+1RNBcmBUxOSxl418H+ifYwyus8mA9ItQohfomsEa1qzxBfVBtEJgI9BVPLPaEJ2YEsFQqfjoeJz+bMcvsdf47foUXWjVmHe0lPyF3cRj8AQzsPQM0FzGLEyqd8gB/JOyuAPmRCVCSPJGvqNpWNa5lO5dfwmRXO/6IJaRIyhczc0qJWqtcbt4ykS3s6xjsJR1aoGXzbYDg8xEUV+iFJ7tEI0O7IEsG5JMDjWGTQelHsfP/zWdMcqfOWcYEr/zhpDoZcJFJ5ZNh1K7zs93W49rTYudGMhaHeo45z4yXIAHUPY2+lEvgvu6Bx9z94tfA88zX43xx3OBeeMrHjJCJHoMdH20iSnH1bqQUgF389VmePp3HUgGxECKSavPjH3Y/sG6Vs5Pzb/iwd8W5GHi/OXlqZAkVPT0zp++LYCNeUOTmWLfuXYDnAIoCOPpT8M2bZlU5RXV+4X6GmOsxAOYCu4S5s+GwpUvXZJfGj9+yzw5SNyzALmjQyA2lFFF41myWbUZL8VpLY0QTAb5I5QfCf0kb4wQsHipByXplNiG2nw9npIgbQUcEewYOW+ddI="
    # #SEXY_SETTINGS=driver=sauce,mailgun_api_key=secret,mailgun_key=secret,sl_user=secret,sl_api_key=secret,cloud_auth_login=secret,cloud_auth_pass=secret
    # - secure: "DkigmgVTg0pm79sZxG0sX/uA0kfHQ2RdQR2wYHw5BHmrFr7k7c3myfDcvrwmOGgfx2MX8uaatSWsrfFcWNH5LXCaSn/W3pA61RNu4XBhfHTwSXBQrETuxudd9nEdDv7lc8ZyxYXU4/KpkhkACCemDu7em8yPpqUwNCFVZkM69bBczhAsExrJv/N14RwJJ4+45I3NflF9N7yT6/9LaW+y2es0UL7S9YnQT/1TzQ3jTXz13kpG2WPJ+47QwHDQvaZq/xhJP40iM/h5hnlpPw4MA2JlrlVkbS7GXg68SYoPOHJWOReX1VCCfyR1OvlnJxZk6FYrEJTO40Q/vOCiWLMaEBOfFLjQAEjsWJFxNvO3Zwv1wDl7ouJGxlDQbM0rNw3R8SxSzvnb89TturRf1x9jB6DOQT8KV9kIbT9XNp0DuUYLMjRQ5f96ABc5oMZN9ZYnpNz5aDcVdZmSuSReQsuPGyJZW2eD2S5A2IrrSCm+OcjRe13NxKv6QWdspMVy/IY3GHAPUVQ51/nJ4MDgQBZdsMmfAD3/yrEvQL+b1Zy/nJsAPKP+nN4rowSD+WWgrUGSu3ruQFJsr+H1CQqwdoJmXAYdLpu7jJASoFmRirNo3GzvacOCVChBPDxZTXz2+1yNGMWCha/3toe2uw9YAEMPQXGV0Er3KIx/azsH0itELJw="
    # #SEXY_SETTINGS=driver=testingbot,mailgun_api_key=secret,mailgun_key=secret,cloud_auth_login=secret,cloud_auth_pass=secret
    # - secure: "LGWAKWspJjUTJNxwLk/rqCOtQWlZlaKuQ8mDzMl+GHiKzWqf5yZfq99rbrTdagHDclyuYNGwsYaMTp/r1wYyaGwqi1/u8sbP+v85Hpm9qNlNZ6kzz9BExgPl9EE9isNu0wqcoSu8NMvR7xL/r/yxaYQpw6JU0+X7PB/hjKiLdafwxaH15xV/6btrXHx+PgtPmsXCP74KJG2TdFBEUBjWJG05TjNduxYjyPhX6GNFqgdOpTuvFiWI28t9BLUvx2BiMI9cnt2RIRo+mXQUQixAmp4Hhtm+0fFHHS42kqtmogkladrjzJivN3CcxNmf6CteWSLcGlCR9Oz3sIceC7MhzcHjeBu0zjVnOHIBXMLFInEjfAzJKvLzZ0XHcfYbUCqVKXMF/7i8rkuGGVf5XwcqYjFPGXghKWKc83mH0cFG1bcmq+yRKToop33WC8kvTLCE0TxGleZ+Cwi8EVcyXtwfk/WGQaftypUhP+ETOfg7QCRL/2+wLyxXq+GsdlwvcXS1hF93Cag0woqhkLWzqS9NE5du0ScLnSwT0RIS1qhR1/VyLcb20+wlw5vmiQC1xsPhXhkq62XI7Pka5gSPKRLm168N4W7yB4pQ/lcAnO3kdlO3bVgeCaSvHuHbudez1jXaj3tHv+oTbyMMi602DEHMfu8xqQEkw5AhoInhwLe4WqU="
    # #SEXY_SETTINGS=driver=browserstack,mailgun_api_key=secret,mailgun_key=secret,cloud_auth_login=secret,cloud_auth_pass=secret
    # - secure: "ecYr2oUvBpvnEaVcJoROO/BjfGo5wpaUe1b63od9ulOa4wbZHvgUSbaWcluh+P517IbIqryBotrr24JVyGGea8LK8SOozXqJ9zjuhccUYdg5Hwwi5IdNAzoOCueTFz5T99b5NbOXA5QdXqz9hBks5GgfRLduzAkagG3tpP2tKmFqYp5+aWUdafud7iUeLPt/NRbqw+b7xvNLPUdPbSXSfB/mnpXhNBVPcYpxRV2C/dzgpz9qkW2oXzjS/st7K8Ob+W5laOROZU+E0m5fp+3qvAmAVSRKKwQKMOPOGqYignGwyZ3Ddho+rBpS8OkWiu9nIt/0ap0Xj96F+IgMBrufsSGx4GeOtDGuVAGOQWm+5aPcWLFull/4VX5LQApgNcxygNkcpyp0yB6VXHWi7egO7lQlWDMh146ZzEF+nEkEkae/o2ou3k4f54t3xS7XGIIFE8GP7t01WcP4tHg1pNfmXxJd0ezapoBE2Ht3k0bcIWDeSQcPJUzJ9wN4/Ed6TgVS5+Hg76c7YknTjdmwS0Hk8hlfvhUdUL2qR7hoq4bxZ5I6qYVjV2N1COSnRUAJrQ8xUsuoRxgIXhhYlC1Z6RLmnOsuf2Hhi5GvgVr6bD9Enyd6rL4Ikw9tzgoNZz4L0fUPMnZgpgcuItvnxZgZw9yN9bxb2HHznoh6TnXRWXxmDlg="
    # #SEXY_SETTINGS=driver=crossbrowsertesting,mailgun_api_key=secret,mailgun_key=secret,cloud_auth_login=secret,cloud_auth_pass=secret
    # - secure: "hO4sR2WaRx8B6kkI3V9PtoxnaQlZu9ryoRDwO5MyZHZEjsSCatKKjeT0tYiJakiUGDmrOBD0pipzohw6Xmgc0AGMs1LnQJDNvBQS1my7n5uk/C0vM/Yzt599kfTYFnxapHPGxjqM4pnO9Z0Tc29hclFXcCfUf6WNUE6q6n54MddWU1bTfAONE/xOJtXcuKVnJKsRg1V3lvKlBWuiiCIX1WVoxiArFsU27/VPZqwk/7SJksTcNmzs3ayBtsqc00SF3PKJvbZF/vJ3VVA63ofZJejIUCDkyJzennJDE/oeEPtIgbMnK9BrBKeOO0Y0i+gGCERNitbjzv2mGZvCJro6rtJn+0OtqIkuRYb+JtS6Fw7mZqeANLLrEvexbCxnsOM/s7kIK5LIPD27HUJe9q5xBQjjTTDxwdD1gfX1OyrdC+kr/BRVRnpIIzQwwCceurOCrAavr16optJMF/+84te3Of+8HfsHzLFwkOz/C86Vx0Q+nDwhVGviGjjncXEc0loZ2iKcyl+ws4qL2iO+t9LCTZyjDTBsVYCtWNO6js/AuYRLsB8/a2BMvCdrzHi/+nVM735y092nCSF+/J4QP4JRJLJUSfu6h29BEVOndukFDqKlXdDmU32BxqtmDTcJHZYhekVIT8xEazvBWD6JTwuzA+6PZ08jhaqt1x/G2l0cU68="
    # #SEXY_SETTINGS=driver=apium,appium_url=secret
    # - secure: "eZXyJa78UJZPUoBAj7NCm7cc38IAO8zPozwZzQssM5AxocS4njwbqgI7riuQkzsDt5gfcKF099vGyOgb43fpeEJqRanuTdu4Lv0nNgmPtUIqacBhVyk5eFsCgKXbVgVeHYsFPglnl8aw9CwfGjSF8Ir47+Cc4oSZnwVA5blRW0+J9NbA/8PutV2Hs+tV6VuDXKk19G6cmTp0WgmCux02h6S6I3RlporuXKJvp9tF3etHoOTsvhb0/vWho3lryGooHVqLF1x9MvvLPSV4pnKOv5aQMfQwifdzixcjA8W0QdCb0a29HO0Tc7KKxkQPN2oLvLXYJ/dVXBz63xGtVmNYy2IUrsli36qNNFofMx9X6vsvCz+FV7igYYwZFDKpaDWfN+ZutobKbi6fBd4VAtfSbOwwHvTIQK0M0q+9htXLIhiJkPf711Lr9wOOFS+zgAO8KDYbWyfDlr6s0yukZtb251O0qHQqjedMkV+MJe/L3m//xCHj+HzfDZhk83isFUD+AHCF7pkSLbAonsoE3PhFL4AaOt5siTV2HsFTQX+1WvWGy1WQWPvZMa0JgiY5x0RihcqWC62MFNWZgN7e5x0pqf8pPswNVJDSSOOkkI3AcZlga+CfCfWUM6VgjfeDSfvXjumiAJWyimL11nnWK48RyZ080rbSQgzlz96DF3dFxDQ="
    # #SEXY_SETTINGS=driver=headless_firefox,mailgun_api_key=secret,mailgun_key=secret

script: "./scripts/run-tests.sh"

addons:
  chrome: stable
  firefox: latest
  artifacts:
    key:
      secure: "tl9wQBEixzs8Aun9J/yI1LlfROy8ADrieKq+Uz2XMuTGVKnNVAhBBF0JuVJmQjtL+xt28fNWNQZ/YaZLgd3kj5PAe0zQB6oPbkexLcS00JzMul2YvGCNviFeJVmSN8Fh1h6Z98ePTm7Uk4Hypx2DMResCzjKXsbDGev81ZIz3QYhlPemb5+ngq8bzOsjEuS/iymK224IDOcZ8VMfg5Xy+ICH70euB0d2N5iFOw7treRYdd7cSu72izG/j6JmjMGe1I77zk7WKWqg4powY4nHmCxz4X9+djXdd9+132OQ00WoQd2sWLZ82OKfwDAuOFRFSBY14hMu36lROGdHBjjggK7YqblY1KajuDYsq/j21y1tAGDLcDprcxoTCNnt22bAKjkxOciKmfvB+5Tl6OVZALo4pmNNInMK/fiTAH7HKwHRtW1XLOwa9FH6AQWlt6WWEwAU/X0HUEPQ1hmXJUVFe96oAPGJaPZPl3EAalfWKoTtJgMXq/5ltZyAX76rlex9zs4V6FJrIty3KyRyTiy2krXG60SRDGDzWWxH1n0Rt0GlRM5FvEEn8wKTJ0dY3qk6AZ5tviwZu698q25VcZ+6q35tgBZT+TN5I/vWh5XpTaoZ14cGkXhw5BUcI8sj6Gckciomj5C2jqaj6hxnUtBd2TNCfarBuPn1imOFUlAxo8s="
    secret:
      secure: "Z9lVKJmztSwaXr9/sWBmbJKDRcqfEj9ESFAt7NVbNTMcLo1CPsc2hJLdl/YjuqpBNbshFe2FtP+3es6vkzkFMow4+SiuDtu5H+v7SeC17XgDZHeO2gl/ULTIapoBZZJzsAa6CGjbx8zbrhEdjSzUqgOBN6j3CRUniGRFUmsTslf8n+UAm33DwYVwiA4LZBiy5X6vT/qE77sHKieET6m8ZYJPG97RTIgupXYI3zx2nl5JsA+TGduxI4rDEtV+aLiwZCCdN/uImaDz5oQLkQmxyi51E4gczKjN68jNLJSgVyUqRPoiu1cvMIJ5ypaj+Z25+RYZN6T2gMKYNEFl7gMRJ9lRi1mQbsCfmKnGFzMYccBRKHvcdWS4gBOdh3xEuA0s0qazwSrnQo4yWK9+lXX+4p6UTHH/b4fDaqZNFsBgJTGT1+m3tOrakdH3waP5Ij+g0qRWSUK47PSEfwJFp1PkztgIf2vjVDIbzgLOcYr/j5Rsjb+cMYoD4lOSLMcX1EWl6cGkDj4LNE3Il7qMWZGFv4AcsOU8TqBjQk45Va4do94HhARFLfsMijLqCff7dvkaS34IKpMiYWv12ut/XmNTiXmPRnajZ5QLbxMoV/ey/aWJKXaQnJPEulwMsyc4saGzN+i5FsLMk3WnnOl3xDtqpELe9z//uP22VbB1yg2nqgQ="
    bucket: howitzer-example-travis
    paths:
      - $(find log -type f | tr "\n" ":")

