version: 2

jobs:
    build:
      working_directory: ~/howitzer_example
      docker:
        - image: circleci/ruby:2.6.2-browsers
      steps:
        - checkout
        - run: git submodule update --init
    # Restore bundle cache
        - type: cache-restore
          key: example-cucumber-{{ checksum "Gemfile.lock" }}

        # Bundle install dependencies
        - run: bundle install --path vendor/bundle --without webkit

        # Store bundle cache
        - type: cache-save
          key: example-cucumber-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
        - run: bundle exec rake features:smoke
