version: 2

jobs:
    build:
      working_directory: ~/howitzer_example
      docker:
        - image: cimg/ruby:3.0.4-browsers
      steps:
        - checkout
        - run: git submodule update --init
        
        # Restore bundle cache
        - restore_cache:
            keys:
              - v1-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
              - v1-gem-cache-{{ arch }}-{{ .Branch }}-
              - v1-gem-cache-{{ arch }}-

        # Bundle install dependencies
        - run: bundle install
        - run: bundle clean --force

        # Store bundle cache
        - save_cache:
            paths:
              - ~/.bundle
            key: v1-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}

        # Execute tests
        - run: bundle exec rake features:smoke
