<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun_opts = rerun.to_s.strip.empty? ? "--format progress features" : "--format pretty #{rerun}"
std_opts = "--verbose --expand --format html --out=./log/log.html --format junit --out=./log --format pretty features --tags ~@wip --tags ~@bug"
%>
default: -r features <%= std_opts %>  --tags ~@demo features
wip: -r features --tags @wip --wip features
demo: -r features <%= std_opts %> --tags @demo features
bug: -r features --tags @bug --wip features
rerun: <%= rerun_opts %> --format rerun --out rerun.txt --strict --tags ~@wip