###########################################################
#  COMMON SETTINGS                                        #
###########################################################
 debug_mode: false
 page_load_idle_timeout: 20

###########################################################
# APPLICATION SETTINGS                                    #
###########################################################
 app_base_auth_login:
 app_base_auth_pass:
 app_protocol: http
 app_host: demoapp.strongqa.com

 app_test_user: admin@strongqa.com
 app_test_pass: 1234567890
 app_test_user_name: Admin User

 app_api_token: 97f85fa997125c758a67213c44e1c0543a603f3819b31456b9
 app_api_end_point: "api/v1"

###########################################################
# TEST ENVIRONMENTS SETTINGS                              #
###########################################################

 # Specify maximized browser window size
 maximized_window: true

 # Specify one of the following drivers: selenium, selenium_grid, webkit, poltergeist, phantomjs, sauce,
 # testingbot, browserstack
 driver: phantomjs

 # -Selenium-
 # specify one of next browsers: iexplore (ie), firefox (ff), chrome, safari
 selenium_browser: ff

 # -Selenium Grid-
 selenium_hub_url: "http://example.com:4444/wd/hub"

 # -PhantomJS-
 # specify settings for poltergeist
 phantom_ignore_js_errors: false
 phantom_ignore_ssl_errors: true

###########################################################
# Cloud-based Cross-browser Services                      #
###########################################################
 cloud_auth_login: some_user_or_client_key
 cloud_auth_pass: api_key_or_api_secret_or_access_key
 cloud_platform: any
 cloud_browser_name: Chrome
 cloud_browser_version: '31'
 cloud_max_duration: '1800'
 cloud_http_idle_timeout: 40

 # -SauceLabs- (https://wiki.saucelabs.com/display/DOCS/Test+Configuration+Options)
 cloud_sauce_record_screenshots: false
 cloud_sauce_idle_timeout: '180'
 cloud_sauce_video_upload_on_pass: false

 # -TestingBot- (https://testingbot.com/support/other/test-options)
 cloud_testingbot_idle_timeout: '180'
 cloud_testingbot_screenshots: false

 # -BrowserStack (https://www.browserstack.com/automate/capabilities)
 cloud_bstack_resolution: '1024x768'
 cloud_bstack_project: 'Howitzer Example'
 cloud_bstack_build: 'v1'
 cloud_bstack_resolution: '1024x768'
 cloud_bstack_mobile_device:

###########################################################
# CAPYBARA SETTINGS                                       #
###########################################################
 capybara_wait_time: 20

###########################################################
# LOGGER SETTINGS                                         #
###########################################################
 log_dir: "log"
 html_log: log.html
 selenium_server_log: selenium-server.log
 required_clean_logs: true
 hide_datetime_from_log: false

###########################################################
# MAIL SETTINGS                                           #
###########################################################
 mail_adapter: mailgun
 mailgun_key: key-fdc7dfaf228e6c6827ebe94da27125b6
 mailgun_domain: mg.strongqa.com
 mailgun_idle_timeout: 60
 mailgun_sleep_time: 3
